<section>
    
    <h2>Pour toute demande d'informations</h2>
    
        <article class="contact">
            
            <h3>Coordonnées Elise Estrade</h3>
            
                <div class="coordonates">
                    <p>Téléphone : 06/06/06/06/06</p>
                    <p>Email : estradeelise@gmail.com</p>
                    <p>Adresse : 3 rue de balalalala 22000 blablabla</p>
                </div>
                
        </article>
        
</section>