<section class="mySelf">
    
    <h2>Mon parcours de vie</h2>
    
        <h3>J’ai 42 ans, je suis maman de 4 enfants et avant tout une femme épanouie aujourd’hui.</h3>
    
            <article>
        
                <p>Comme la plupart des gens, cela n’a pas toujours été le cas, j’ai connu de grands moments de joies dans ma vie (des réussites, la naissance de mes enfants, mon mariage…), mais aussi des moments douloureux (des échecs, les deuils…).</p>
                <p>Fort de ma reconversion professionnelle en tant que formatrice en 2018, et certifiée «praticienne en bilan de compétences» en janvier 2022.</p>
                <p>Mon évolution professionnelle vers le métier de l’accompagnement, le coaching et plus particulièrement «la parentalité», a été forgé tout au long de ma vie personnelle et professionnelle.</p>
                <p>J’ai surmonté la perte de mon papa à l’adolescence.</p>
        
        
            </article>
    
        <h3>J’ai compris que je voulais venir en aide aux enfants lors de mes 10 années en tant qu’assistance maternelle.</h3>
    
            <article>
        
                <p>Lors de cette expérience professionnelle, j’ai constaté la difficulté qu’éprouve un enfant (peu importe son âge) à faire face aux évènements qui surviennent dans sa vie.</p>
                <p>J’ai gardé beaucoup d’enfants, certains m’ont marqué plus que les autres:
                    - une fratrie (de 3 et 5 ans) a perdu leur maman dans un accident de la route
                    - un enfant était suivi par une assistante sociale (climat familial difficile)
                    - d’autres ont vécu des divorces
                    - d’autres des problèmes de santé, de société (harcèlement)…</p>
            
        
            </article>
    
        <h3>Mes valeurs</h3>
    
            <article>
                <p>Je suis bienveillante, à l’écoute des personnes sans aucun jugement.
            La patience, l’empathie et le calme me caractérise.</p> 
                <p>J’aime mon métier de coach.</p> 
                <p>Accompagner les personnes à réussir, à être heureux, à oser changer, à se valoriser me tient à cœur.</p>
            </article>
    
</section>